# Generated by Django 2.0.7 on 2018-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='primary_out_of_hours_contact',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='secondary_out_of_hours_contact',
        ),
        migrations.AddField(
            model_name='organisation',
            name='out_of_hours_contacts',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.OutOfHoursContact'),
        ),
    ]
