# Generated by Django 2.0.7 on 2018-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180804_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofhourscontact',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='out_of_hours_contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='out_of_hours_org', to='contacts.OutOfHoursContact'),
        ),
    ]
