# Generated by Django 2.0.7 on 2018-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180805_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='IATA code'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ICAO code'),
        ),
    ]
