# Generated by Django 2.0.7 on 2018-08-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180805_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutOfHoursContact',
            new_name='KeyContact',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='out_of_hours_contacts',
        ),
        migrations.AddField(
            model_name='organisation',
            name='key_contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='key_contacts_org', to='contacts.KeyContact'),
        ),
    ]
