# Generated by Django 2.0.7 on 2018-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20180806_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycontact',
            name='notes',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='keycontact',
            name='tfh',
            field=models.BooleanField(default=False),
        ),
    ]
